### ISSUE TITLE
mysql  Ver 8.0.15 incompatablility 

### ISSUE THREAD

**Issue by icemanshutter** [domainmod/domainmod#100]
Password function in mysql is deprecated so the login doesn't work.

Also had some issue because of the caching_SHA2_Password being used by mysql version 8 

tested with mysql  Ver 8.0.15 for Linux on x86_64 (MySQL Community Server - GPL)

**Comment by ThatOhio** [comment]
It looks like I'm having the same issue, +1

**Comment by chetcuti** [comment]
The password functions were recently updated, and I believe these were resolved, so you may want to take a look at the newest version (v4.14.0).
