### ISSUE TITLE
General error: 2014  - not able to add "Domain Registrar Fees"

### ISSUE THREAD

**Issue by nixjobin** [domainmod/domainmod#101]
After updating to the latest version today with git pull, I'm not able to update the missing registrar fees, log below. 

`[Fri Apr 26 07:51:18.837053 2019] [php7:error] [pid 16432] [client 162.158.14.24:45600] PHP Fatal error:  Uncaught PDOException: SQLSTATE[HY000]: General error: 2014 Cannot execute queries while other unbuffered queries are active.  Consider using PDOStatement::fetchAll().  Alternatively, if your code is only ever going to run against mysql, you may enable query buffering by setting the PDO::MYSQL_ATTR_USE_BUFFERED_QUERY attribute. in /home/user1/public_html/classes/DomainMOD/Conversion.php:120\nStack trace:\n#0 /home/user1/public_html/classes/DomainMOD/Conversion.php(120): PDO->prepare('\\n              ...')\n#1 /home/user1/public_html/classes/DomainMOD/Conversion.php(73): DomainMOD\\Conversion->updateConversionRate(1, '1', '106', '1')\n#2 /home/user1/public_html/maintenance/update-conversions.php(40): DomainMOD\\Conversion->updateRates('USD', '1')\n#3 {main}\n  thrown in /home/user1/public_html/classes/DomainMOD/Conversion.php on line 120, referer: https://assets.example.com/maintenance/index.php
`

As a Workaround, ran "git checkout v4.00.000" to downgrade the version and it is working fine.

**Comment by chetcuti** [comment]
This is a known issue that only seems to affect certain people, and even with the recommended fixes implemented, it still causes issues for some. It's really quite bizarre. I've gone ahead and implemented a temporary fix until the issue can be fully resolved, and the fix will be released in v4.15, which should be out in the next week or two.

If you're looking for some more information on this isuse here's the thread from the forum: https://groups.google.com/forum/#!msg/domainmod/sXCgOUF0yvg/bsZs8SJwAwAJ
