### ISSUE TITLE
Errors with Currency API's

### ISSUE THREAD

**Issue by MartinGoode** [domainmod/domainmod#102]
Hi,

The Free Currency Convertor API errors with 'bad request' and going to the URL manually says an API key is needed.
```
"Last Error":"file_get_contents(https://free.currencyconverterapi.com/api/v5/convert?q=GBP_USD&amp;compact=y): failed to open stream: HTTP request failed! HTTP/1.1 400 Bad request
", "User ID":"1", "Currency ID":"106", "Conversion Rate":"1", "Update Time":"2019-05-22 10:36:13"
```

The Exchange Rates API errors with 'redirection limit' but going to this url directly works.
```
`"Last Error":"file_get_contents(https://api.exchangeratesapi.io/latest?base=GBP&amp;symbols=USD): failed to open stream: Redirection limit reached, aborting", "User ID":"1", "Currency ID":"106", "Conversion Rate":"1", "Update Time":"2019-05-22 10:37:37"`
```

**Comment by shukrihd** [comment]
Yep. Having the same issue.

**Comment by chetcuti** [comment]
Unfortunately with them now requiring an API Key, there's no way to fix the issue with the Free Currency Converter API. FCCA has been completely removed from DomainMOD as of v4.14.0, which was release yesterday.

As for the Exhange Rates API, I wonder if this error may have been something temporary, as it seems to be working fine now and no matter what I try I'm unable to reproduce the error on my end.
