### ISSUE TITLE
Add Web Hosting in Homepage

### ISSUE THREAD

**Issue by Prathamesh2691** [domainmod/domainmod#104]
Hi Team,

Can you please add Web Hosting in Dashboard Home. As sometimes we have hosting associated with the different third-party provider than the Domain Provider. that's the reason I want Web Hosting in Homepage with the dedcated layout for pending, expired sections

**Comment by Quin452** [comment]
Realised there is the google forum which is a better place for this.

**Comment by chetcuti** [comment]
This is something that's planned for the future. Eventually I want all pieces of data that could potentially have a cost (web hosting, DNS services, etc.) to be worked into the system like Domains and SSL Certificates are. It's going to mean some pretty big rewrites to the software though, so it may be a bit of time, but it's definitely planned.
