### ISSUE TITLE
Compare the registrars fees

### ISSUE THREAD

**Issue by WhiteTiger-IT** [domainmod/domainmod#106]
It would be useful to be able to compare the fees of the different registrars.  
A custom table where horizontally it is possible to insert the registrars, while vertically we find the TLDs.

For Example
```
           Reg1       Reg2       Reg3, ...
.com      10       9       12
.net      5       5        6
.org      5        6       8
...
```

**Comment by chetcuti** [comment]
This is something that I absolutely plan to implement in the future, exactly for the reason you mention. It would be nice if users, when registering a new domain, could quickly and easily see which registrar gives them the best price on that specific TLD. It could also compare registrar features for that TLD, like if it offers WHOIS privacy and if it has a cost.
