### ISSUE TITLE
Problems with "umlaut"-Domains

### ISSUE THREAD

**Issue by sirferl** [domainmod/domainmod#107]
Hi,
first of all: a very useful tool with good features. Thank you for making it available.
We have a few domains with "umlauts" in the name.
Here domainmod is a bit inconsistent in handling:

If I bulk add them, the umlaut is converted to the URL-Representation:
österreichselfie.at becomes %C3%B6sterreichselfie.at
If I want to bulk modify them, it is not found if I enter the URL-Representation in the list.

If I enter the domain manually with an umlaut, I cannot use segment filters, because there it is again converted to the url-format no matter what I enter.

thank you for considering this problem
regards
ferdinand

**Comment by chetcuti** [comment]
A fix for this has been implemented in the development version, and it should be getting pushed out in a new official release (v4.15) within the next week.

Thanks for the report!
