### ISSUE TITLE
[EMERGENCY] A new version is NEEDED and IMPORTANT with all VULNERABILITY patches

### ISSUE THREAD

**Issue by Neustradamus** [domainmod/domainmod#114]
All are solved?
- https://www.cvedetails.com/vulnerability-list/vendor_id-18008/product_id-46254/Domainmod-Domainmod.html

Linked to:
- https://github.com/domainmod/domainmod/issues/108
- https://github.com/domainmod/domainmod/issues/110
- https://github.com/domainmod/domainmod/issues/111

**Comment by Neustradamus** [comment]
@chetcuti: Happy New Year 2020!

Any news about Summer 2019 Vulnerabilities?

**Comment by Neustradamus** [comment]
Any news?

**Comment by chetcuti** [comment]
These issues were resolved in DomainMOD v4.14.0, which was released yesterday.
