### ISSUE TITLE
Not sure if this counts as a bug. Missing entry in the corresponding apache2.conf for DomainMOD

### ISSUE THREAD

**Issue by Dardwizzle** [domainmod/domainmod#115]
Hi Guys, 

First I would like to say, thank you for this wonderful application. It's amazing, and was a breeze to install, setup, and took a little bit to get used to using it, but it's one of my most valued tools!

I was trying to figure out what a specific parameter was so I clicked on the link on the Left Hand Menu for Documents. When I did, I got an error saying that I was forbidden from accessing the doc/userguide/ 

It turned out that when the instructions I used for the installation (which came from here, but I was unable to find where now that I want to tell you) that the virtualdomain.conf for apache2
gave and example to use the basic DirectoryIndex for the index.php only, however, the userguide directory uses index.html

So if someone could update the installation instructions to change the following line in their virtualdomains.conf file

From: 
 DirectoryIndex index.php

To:
 DirectoryIndex index.php index.html

Save the file and restart apache2

systemctl restart apache2

Thank you much!

JD

**Comment by chetcuti** [comment]
I think most servers should be setup to support both .php and .html, but just in case, and to make this even easier for users, I'm going to rename the documentation .html files to .php going forward. So nobody should have to worry about including support for .html if it isn't already included.
