### ISSUE TITLE
Entering a space for username allows to save

### ISSUE THREAD

**Issue by Quin452** [domainmod/domainmod#118]
Not that I really mind this, because it does what I want, but I've added Let's Encrypt as a SSL Provider (which it is).

This doesn't need a user or password to install certs, and so, I simply put a space in the required username field.

I was able to save, but unable to go to that account anymore.

**Comment by chetcuti** [comment]
Thanks for bringing this to my attention! I do apologize, but I've implemented a fix for this (and related issues), which will be out in v4.15.

When you upgrade to v4.15, any blank usernames will change to "n/a", along with any other blank fields that some validation was added for.
