### ISSUE TITLE
Custom Field

### ISSUE THREAD

**Issue by shirospyro** [domainmod/domainmod#121]
Hi, is it possible to make the custom field visible to all users instead of the current user itself?

**Comment by chetcuti** [comment]
Are you still experiencing this issue? Custom Fields should be visible to every user who has access to the system, so if that's not the case something may have gone wrong with your installation.

If you're still having an issue with Custom Fields feel free to reopen this issue and supply some further details details regarding the problem and I will try to investigate further.
