### ISSUE TITLE
Automatically manage domain transfers across registrars?

### ISSUE THREAD

**Issue by johnnyutahh** [domainmod/domainmod#123]
Can domainmod or any of its competitors automatically manage domain transfers across registrars?

Still very useful if not. For now, I'm doing a bit of due diligence before I install.

**Comment by chetcuti** [comment]
DomainMOD isn't able to help with transfers, but that would be part of the plan eventually. Something like that is probably pretty far down the road though.

To be honest I'm not sure about competitors. I know Efty helps you manage your domains, but I believe they're more of a sales platform and I'm not sure if they help with transfers.
