### ISSUE TITLE
Unable to login

### ISSUE THREAD

**Issue by yohoho18** [domainmod/domainmod#124]
I've installed DomainMod on ubuntu 18.04 with PHP 7.2 . But after entering correct username and password it doesn't proceed to next page instead it show error page with "HTTP error : 500". Is there any suggestion regarding this issue. 

Thanks.

**Comment by chetcuti** [comment]
You may need to check your web server/PHP logs for more specific details about the issue. Unfortuntaely error 500 ("Internal Server Error") covers a wide range of issues, so it's very difficult to troubleshoot without more information.
