### ISSUE TITLE
Database upgrade error

### ISSUE THREAD

**Issue by Qrzysio** [domainmod/domainmod#125]
I've got a crash while upgrading database from v4.13 to v4.14. 

It turns out my browser (the newest Firefox) returns `NULL` from `$_SERVER['HTTP_ACCEPT_LANGUAGE']`. 

Have a look into file `classes/DomainMOD/Goal.php`. 
Line 65: `$act_language = $_SERVER['HTTP_ACCEPT_LANGUAGE'];`

I recommend to replace it with:
`$act_language = $_SERVER['HTTP_ACCEPT_LANGUAGE'] ?? 'en';`

**Comment by chetcuti** [comment]
This has been updated and will be included in the next release of DomainMOD.

Thanks for the report!
