### ISSUE TITLE
PHP Fetal error: Uncaught PDOException: SQLSTATE[HY000] [2002]

### ISSUE THREAD

**Issue by sotiriskoletsios** [domainmod/domainmod#130]
I am trying to install to an ubuntu 20.04 server with mysql and PHP v7.4 and I get this error: 
 [php7:error] [pid 69826] [client ###.###.###.###:59647] PHP Fatal error:  Uncaught PDOException: SQLSTATE[HY000] [2002] No such file or directory in #FILEPATH#/classes/DomainMOD/Database.php:33\nStack trace:\n#0 #FILEPATH#/classes/DomainMOD/Database.php(33): PDO->__construct()\n#1 #FILEPATH#/classes/DomainMOD/Database.php(46): DomainMOD\\Database->__construct()\n#2 #FILEPATH#/index.php(29): DomainMOD\\Database::getInstance()\n#3 {main}\n  thrown in #FILEPATH#/classes/DomainMOD/Database.php on line 33
 
Any solutions?

**Comment by chetcuti** [comment]
This particular error, "SQLSTATE[HY000] [2002]" will be related to your MySQL or MariaDB connection settings:

https://stackoverflow.com/questions/29395452/php-connection-failed-sqlstatehy000-2002-connection-refused

https://stackoverflow.com/questions/35394230/sqlstatehy000-2002-connection-refused-within-laravel-homestead
