### ISSUE TITLE
[Feature Request] URL Custom Field Types & American Date Option

### ISSUE THREAD

**Issue by Shane8johnson** [domainmod/domainmod#131]
Hi, 
It would be really great to add a URL as a custom field type so that way It becomes clickable on the Domains screen. Currently, Custom Field Types are: Check Box, Date, Text Field, Text Area, Time Stamp.
This is useful to maybe add the Cpanel URL, or a URL to a backup hosted elsewhere, or just anything that you need a URL for. 

Additionally, adding a setting for American Dates would be apricated. The standard in America would be MM/DD/YYYY or 02/16/2021 for example. 

Great work! Thanks!

**Comment by chetcuti** [comment]
Oh! Great idea with the URL custom data type, I think that would be a very nice addition to the custom fields, and it should be pretty easy to implement. I'll investigate and try to get this into the next release.

Regarding the date formatting, that's something I've wanted to add for quite a while now, and I think the groundwork was laid when multilingual support was added, so I'm definitely going to investigate this again and see how much work it'll be to implement.

**Comment by chetcuti** [comment]
The URL custom field type was added to DomainMOD [v4.17](https://github.com/domainmod/domainmod/releases/tag/v4.17.0), which was released earlier today. Thanks again for the suggestion!
