### ISSUE TITLE
Does not work with Mariadb 10 through softaculous

### ISSUE THREAD

**Issue by outerregion** [domainmod/domainmod#132]
When trying to install with Mariadb installed, the error 
```
The following errors were found :

    Required MYSQL version less than 8.0.0 AND found version is : 10.5.8
```

comes up, preventing install. 

This is likely related to the ubuntu 20.10 issue as well since that comes default with mariadb 10.

**Comment by xsname** [comment]
That is softaculous issue afaik. I managed to install it by adding a hook in softaculous configuration files and defined fake mysql version number to override this check. More details you can find here https://www.softaculous.com/docs/admin/hooks/#Define_MySQL_Version

**Comment by matt-sawyers** [comment]
having the same issue.
<img width="1054" alt="Screen Shot 2021-05-23 at 3 21 47 AM" src="https://user-images.githubusercontent.com/1031567/119259428-e87c9f00-bb93-11eb-8a94-941e3a5532d4.png">

**Comment by chetcuti** [comment]
As much as I would love to help, we've had this issue reported a few times now and it seems to be specific to Softaculous, which unfortunately I have no control over. I'm going to reach out to them to see if they might know what's going on here.

I'll hopefully have an update soon!

**Comment by chetcuti** [comment]
Another report of the same issue: https://groups.google.com/g/domainmod/c/pmoKPdJ7sv0/m/2dghoSIPAQAJ

**Comment by chetcuti** [comment]
Softaculous has implemented a fix for this, so you should no longer experience this issue.

Please let me know if you experience any other similar issues.
