### ISSUE TITLE
Cron job error

### ISSUE THREAD

**Issue by xsname** [domainmod/domainmod#133]
I suspected that I am having some issues with cronjob then I piped the output to a text file and found this. Please advise

<b>Fatal error</b>:  Directive 'allow_call_time_pass_reference' is no longer available in PHP in <b>Unknown</b> on line <b>0</b><br />

I am using php 7.4 via cloudlinux

**Comment by chetcuti** [comment]
It sounds like you may have a **very** deprecated PHP settings in one of your PHP configuration files.

https://stackoverflow.com/questions/12946835/directive-allow-call-time-pass-reference-warning
