### ISSUE TITLE
[Feature Request] Support Cloudflare Registrar 

### ISSUE THREAD

**Issue by moose999** [domainmod/domainmod#135]
Hi,

Many thanks for domainmod, its very useful for me to manage all our domains across the providers!

Although Cloudflare only supports domain transfer and not direct purchase for domains, it would be really useful to be able to include Cloudflare-registered domains in domainmod. 

The relevant Cloudflare documentation is here https://api.cloudflare.com/#registrar-domains-properties

Is it possible to extend domainmod to support Cloudflare registrar?

Many thanks again!!

**Comment by chetcuti** [comment]
I'll have to dig into the API docs a bit more, but on first glance I'm not sure if they return all of the information needed to import everything into DomainMOD. Some of it definitely, but I couldn't find some of the information, but I'll see if I can make it work somehow.

**Comment by JOHLC** [comment]
Also interested

**Comment by moose999** [comment]
CloudFlare now supports registration too, so would be a really great feature!

**Comment by sebstrgg** [comment]
This would be great! +1

**Comment by wordskill** [comment]
I would be delighted too.

Cloudflare Registrar is growing fast and its zero-profit pricing makes it attractive to precisely the sort of domainer, with lots of domains, who would be likely to use DomainMOD.

Personally, apart from saving money on renewals, I find it very handy to be able to use their other services to support each domain, and the number of services keeps growing. They recently added catchall email handling (including DMARC etc) for the free tier. Even better, Cloudflare Pages allow you to quickly set up a free, highly performant site for each domain.

**Comment by ctrlbrk42** [comment]
+1

Cloudflare quickly getting all my domains, since they sell at cost and have a good interface.

**Comment by chetcuti** [comment]
Cloudflare support will be included in DomainMOD v4.19, which will be released within the next couple of weeks.

Check our support portal for updates: https://support.domainmod.org/b/90pj1r0j/domainmod-support/add-cloudflare-api-support
