### ISSUE TITLE
Fatal error: Uncaught PDOException: SQLSTATE[HY000]: General error: 1364

### ISSUE THREAD

**Issue by KevinZuccaro** [domainmod/domainmod#136]
Fatal error: Uncaught PDOException: SQLSTATE[HY000]: General error: 1364 Field 'notes' doesn't have a default value in /membri/kevinzuccaro/domainmod/install/go.php:223 Stack trace: #0 /membri/kevinzuccaro/domainmod/install/go.php(223): PDOStatement->execute() #1 {main} thrown in /membri/kevinzuccaro/domainmod/install/go.php on line 223

**Comment by chetcuti** [comment]
You'll need to disable MySQL strict mode in order to get rid of this other other similar warnings.

https://domainmod.org/docs/userguide/troubleshooting/#strictmode
