### ISSUE TITLE
[Feature Request] Support Onlinenic Registrar

### ISSUE THREAD

**Issue by Bernardino18** [domainmod/domainmod#139]
Hi,
Thanks to the amazing project that helps alot of people.

Is it possible to extend domainmod to support Onlinenic registrar?

API Documentation: https://onlinenic.com/cp_english/template_api/api_help.php

**Comment by chetcuti** [comment]
OnlineNIC has been requested in the past as well, and we've got it logged in our support portal. I'd recommend coming on over and voting on the issue so it climbs up our roadmap faster.

https://support.domainmod.org/b/90pj1r0j/domainmod-support/add-onlinenic-api-support
