### ISSUE TITLE
[Feature Request] Support Netim Registrar

### ISSUE THREAD

**Issue by Bernardino18** [domainmod/domainmod#140]
Hi,
Thanks to the amazing project that helps alot of people.

Is it possible to extend domainmod to support Netim registrar?

API Documentation: https://support.netim.com/en/wiki/API_2.0

**Comment by chetcuti** [comment]
I've officially added Netim to our roadmap. Come on over and vote if you'd like to help it get worked on sooner!

https://support.domainmod.org/b/90pj1r0j/domainmod-support/add-netim-api-support
