### ISSUE TITLE
Found a possible security concern

### ISSUE THREAD

**Issue by zidingz** [domainmod/domainmod#142]
Hey there!

I belong to an open source security research community, and a member (@0x7zed) has found an issue, but doesn’t know the best way to disclose it.

If not a hassle, might you kindly add a `SECURITY.md` file with an email, or another contact method? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) this best practice to ensure security issues are responsibly disclosed, and it would serve as a simple instruction for security researchers in the future.

Thank you for your consideration, and I look forward to hearing from you!

(cc @huntr-helper)

**Comment by chetcuti** [comment]
I've created a security policy (SECURITY.md) and added it to my project root, and it will be included in the next release of my software, which will be within the next couple weeks.

To disclose a security vulnerability, please feel free to contact me at my personal email address, greg@chetcuti.com

**Comment by JamieSlome** [comment]
@chetcuti - thanks for your response 👍 

It looks like we previously sent some e-mails to [info@domainmod.org](mailto:info@domainmod.org) but didn't get a response. You can find both reports here:

https://huntr.dev/bounties/271e403a-e6bd-4e79-8ae5-c680b08e9489/
https://huntr.dev/bounties/9fed3691-c678-4d08-a546-e99e0b5faa34/

Let me know if you have any questions - happy to support!

**Comment by chetcuti** [comment]
My apologies, I didn't receive your previous emails for some reason.

Thanks for the reports! I've reviewed and commented on each of them.
