### ISSUE TITLE
[API Request] PorkBun API with examples

### ISSUE THREAD

**Issue by rolltidehero** [domainmod/domainmod#144]
They are one of the top registrars in the world. 
#1 for me with over 300 domains registered with them.

Here is a link to their latest API, version 3, with examples for each option.
[https://porkbun.com/api/json/v3/documentation](https://porkbun.com/api/json/v3/documentation)

**Comment by chetcuti** [comment]
Unfortunately Porkbun's API just doesn't return enough information yet.

You can check our support portal for updates: https://support.domainmod.org/b/90pj1r0j/domainmod-support/add-porkbun-api-support
