### ISSUE TITLE
[Feature Request] Support HEXONET Registrar

### ISSUE THREAD

**Issue by papakai** [domainmod/domainmod#145]
Morning!

I would enjoy seeing HEXONET (part of the CentralNic Group PLC) natively shipped with DomainMOD.
Regarding technical details: Just feel free to get in touch with me.

Thanks!
Best
Kai

**Comment by sebstrgg** [comment]
I'd love to see this integration added as well. API documentation can be found here: https://wiki.hexonet.net/wiki/Domain_API

**Comment by papakai** [comment]
Our whole API's commands are covered here:
https://github.com/hexonet/hexonet-api-documentation/tree/master/API

We offer a PHP SDK at github allowing for a more smooth integration.
https://github.com/centralnic-reseller/php-sdk
A demo app with an basic examplary integration of our API communication can be found here:
https://github.com/centralnic-reseller/php-sdk-demo

I am the department lead/lead dev at CentralNic covering 3rd-party software integrations for the reseller brands (HEXONET, RRPproxy mainly). That's why I am the right guy, if you're having questions on how to integrate the best. I can't just contribute more from my side actually as of other priorities on my department's end.

Thanks @sebstrgg for bumping this thread.

**Comment by chetcuti** [comment]
We have the HEXONET API integration on our roadmap, but if you'd like to help it climb up faster you can vote on the integration in our support portal: https://support.domainmod.org/b/90pj1r0j/domainmod-support/add-hexonet-api-support
