### ISSUE TITLE
[Feature Request] Manage domain backorders

### ISSUE THREAD

**Issue by mikaelpelle** [domainmod/domainmod#146]
It would be great to be able to keep track of domains that are in backordering service.
Could you look into adding a 'Backordered' option in the 'Domain Status' ?
These domains would also need to be listed on the Dashboard.

**Comment by chetcuti** [comment]
This is something I've been pondering for a while now. I'm still not 100% sure how I'm going to implement it, but if you want to help it get implemented sooner, or have ideas on what you would like to see in the feature, come on over to our support portal and vote and comment!

https://support.domainmod.org/b/90pj1r0j/domainmod-support/a-watchlistwishlist-to-keep-track-of-external-domains
