### ISSUE TITLE
Suggestion - domain billing

### ISSUE THREAD

**Issue by insxa** [domainmod/domainmod#147]
Can you make something like https://github.com/vityabond/hopebilling/
Its billing system for hosting provider and domain registratioon, except domain search not wotking, i dont know why.
I think its needed to make some good domain billing with search and user registration, managing DNS, contact info, EPP transfer codes.
I think because hopebilling is opensource it can be used and make modifications.
Cause my system only allows hopebilling for domain reselling option it would be great that this billing is functional and better than it was.
It has already freenom module in it like in yours domainmod, so you can comapre and see how it works, i think its very simple, even im not that good in php.
Can you help at least with domain search modification ?

**Comment by chetcuti** [comment]
I like what HopeBilling is doing, and I'm going to keep an eye on the project, but unfortunately I just don't have the time for any new projects myself these days. I'm sure it will have certain things in common with DomainMOD in the future, but for now they're fairly different projects.
