### ISSUE TITLE
Cloudflare?

### ISSUE THREAD

**Issue by m1guelpiedrafita** [domainmod/domainmod#15]
Could you add support for the Cloudflare API?
https://api.cloudflare.com
Thanks!

**Comment by chetcuti** [comment]
I took a look at Cloudflare's API documentation and they seem to be lacking a lot of the information that DomainMOD retrieves (domain expiration date, WHOIS privacy status, auto renewal status), so I'm not sure if they're a good candidate for API integration.

Just in case I'm missing something in their API docs I've contacted their support department with some questions, and I'll update this issue when I hear back from them.

Regarding Cloudflare and domains, I have a feeling that their API is primarily used for DNS information, not actual domain registration information. Hopefully their support will be able to shed some light on this for us.

**Comment by chetcuti** [comment]
Cloudflare got back to me, but unfortunately they can't be implemented into DomainMOD yet. As I suspected the domain side of their business is not available via their API.

"_Cloudflare is not a domain registrar currently although we have ICANN approval we have not started selling domains, so we do not keep that information and therefore it is not available via our API._"
