### ISSUE TITLE
Domain that has been pulled by a csv file, do not shown on the system

### ISSUE THREAD

**Issue by maorweissSV** [domainmod/domainmod#150]
Hi there!

I'm using the newest version of your system - Version 4.19.0.

I've just tried to pull a domain with the Domain CSV Importer feature.
I succeeded. You can see that on the DB and on the Dashboard.
DB:
![image](https://user-images.githubusercontent.com/83959332/168829884-cb8fbdba-f67a-467b-9cfe-8038e9564042.png)

Dash:
![image](https://user-images.githubusercontent.com/83959332/168829922-a585b7bd-964a-4993-b366-e2be18daa1d6.png)

But somehow, cannot reach it on the system.
![image](https://user-images.githubusercontent.com/83959332/168829944-dd53008b-14c7-46d7-9420-089e5396d9a8.png)
![image](https://user-images.githubusercontent.com/83959332/168829959-21b20cef-eed2-4a10-ae32-1040575284fd.png)

What should I do? There's no error msg here...

**Comment by gregdotca** [comment]
I see that this is an older issue from a previous version of DomainMOD. If you haven't already, I'd recommend upgrading to v4.21.0. Or, better yet, if you wait until the end of the week v4.22.0 will be released. Also, whenever possible, we recommend using the Docker/Docker Compose installation method.

I apologize for not responding to this ticket sooner. Life has been a bit crazy the last few years and I haven't had much time to work on DomainMOD, but I'm hoping to change that in 2025.
