### ISSUE TITLE
.day tld not stuck in pending state

### ISSUE THREAD

**Issue by haidars** [domainmod/domainmod#151]
---
# System Information

DomainMOD Version: 4.19.0 (4.19.0)
Local IP Address: 172.23.0.3
Remote IP Address: 102.119.189.120
Web Server OS: Linux c23dd4d67f7a 5.10.102.1-microsoft-standard-WSL2 #1 SMP Wed Mar 2 00:30:59 UTC 2022 x86_64
Web Server Software: Apache/2.4.53 (Debian)
PHP Version: 7.4.29
PHP Error Log Location: /var/www/html/domainmod.log
MySQL Version: 10.5.16-MariaDB-log
MySQL Mode: NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION

Server Software: PHP v5.5+: Pass, MySQL: Pass
PHP Extensions: PDO (MySQL): Enabled, cURL: Enabled, OpenSSL: Enabled, gettext: Enabled
PHP Settings: allow_url_fopen: Enabled

---

Hi,

Am trying to import All domain under my account from cloudflare, All domain are imported successfully except `.day` tld domain.

![image](https://user-images.githubusercontent.com/24551303/185391697-209fccca-c5c2-417a-9194-4c75789db20e.png)

Have try to remove the domain and re-add again, run the cron manually but it still stuck in `Pending State`

Under the debug log, 

![image](https://user-images.githubusercontent.com/24551303/185392231-e9d38fcc-b1a0-41d1-bba3-efa3db300f4a.png)

Regards
haidar

**Comment by gregdotca** [comment]
I see that this is an older issue from a previous version of DomainMOD. If you haven't already, I'd recommend upgrading to v4.21.0. Or, better yet, if you wait until the end of the week v4.22.0 will be released. Also, whenever possible, we recommend using the Docker/Docker Compose installation method.

I apologize for not responding to this ticket sooner. Life has been a bit crazy the last few years and I haven't had much time to work on DomainMOD, but I'm hoping to change that in 2025.
