### ISSUE TITLE
Feature request and contributing ?

### ISSUE THREAD

**Issue by Epy** [domainmod/domainmod#154]
Hello
I really like the features of this software :) I would like to use it but I'm using OVH for now. I know it's in the roadmap

I would like to add OVH API but I'm not able to develop in PHP so, I can't make a PR :( 

Do you have a formatted document to describe an API which could help someone adding it to the app and kind of document it for future updates and other developpers contributing ?

If not, would you be interested in me creating one ?
For example an YAML formatted text file or anything else easy to write and read by humans ?

Are all APIs accessed by code in [domainmod](https://github.com/domainmod/domainmod)/[classes](https://github.com/domainmod/domainmod/tree/master/classes)/DomainMOD/ folder ?
In order to find common points from all of them and describe them accurately.

Thanks

**Comment by wokawoka** [comment]
integrating the OVH API would be gold

**Comment by gregdotca** [comment]
There's an existing submission on our support portal about adding OVH API support, I would recommend keeping an eye on that submission for the OVH API status.

https://support.domainmod.org/b/90pj1r0j/domainmod-support/add-ovh-api-support

Long story short, OVH has the details that DomainMOD needs, but getting setup with API Keys has been way more of a pain than it should be. I currently have a ticket open with OVH to get the issues sorted out so I can get this implemented.
