### ISSUE TITLE
Imported domains from Godaddy API do not show up in the domains list.

### ISSUE THREAD

**Issue by raulpcs** [domainmod/domainmod#155]
Hi,

I imported 150 domains from 3 different Godaddy Accounts using the GoDaddy API.
The Queue Log show my domains with the status: "Successfully Imported".
![image](https://user-images.githubusercontent.com/105060462/212521548-60c585f9-6e4c-433b-922f-ce85d72f7e14.png)

But on the Domains section the domains do not show up.
![image](https://user-images.githubusercontent.com/105060462/212521459-3e6b7f10-9871-4267-8ddc-bf56909c0186.png)

I can only see the domain counts in dashboard the widgets.
![image](https://user-images.githubusercontent.com/105060462/212521451-9ac6c4ef-3a62-4382-b316-2a9103f55e52.png)

I'm running the system on a docker installation using version 4.19.0

**Comment by yarlanda** [comment]
Add your missing fees for the Registars/TLDs. It should work then

**Comment by gregdotca** [comment]
As @yarlanda mentioned, you need to enter the fees for the TLDs you imported, then the domains will be displayed.

![enter_fees](https://github.com/user-attachments/assets/c0d88246-3960-43c4-8069-cd7ade67ec2f)
