### ISSUE TITLE
[Bug] Dynadot API seems broken

### ISSUE THREAD

**Issue by AmirHuxain** [domainmod/domainmod#157]
There are a few changes in the response of the Dynadot API such as `DomainInfoHeader` instead of the existing `ListDomainInfoHeader`, and a little structural change in the domain list API response.

I was able to fix the issue and imported domains successfully. Is this issue already being fixed? Otherwise, I would love to open a PR with changes.

Thanks

**Comment by gregdotca** [comment]
If this is still an issue, I'd recommend upgrading to v4.21.0. Or, better yet, if you wait until the end of the week v4.22.0 will be released.

I just tested v4.21.0 with Dynadot's API and it was able to import and process all of my domains successfully.
