### ISSUE TITLE
[Bug] Domains tab not showing button if delete all domains from Bulk Updater

### ISSUE THREAD

**Issue by Alex-Ferdinand** [domainmod/domainmod#159]
Original
![image](https://user-images.githubusercontent.com/124665819/217498992-7658f4cb-ae83-4245-a164-50c81bb3ab59.png)
After bulk delete domains
![image](https://user-images.githubusercontent.com/124665819/217499276-6a1d6d00-b921-4c15-a4cd-b588a099df37.png)
No buttons
![image](https://user-images.githubusercontent.com/124665819/217499380-a84a6cc1-faf2-4635-97c6-ed9ed2abf828.png)

**Comment by gregdotca** [comment]
Thanks for the report @Alex-Ferdinand!

This issue has been fixed and will be included in v4.22.0, which will be released at the end of the week.
