### ISSUE TITLE
Unable to login

### ISSUE THREAD

**Issue by ilhanyumer** [domainmod/domainmod#160]
I have newly installed DomainMOD and I am unable to login. The issue is this:

[Fri Apr 14 23:49:34.901963 2023] [proxy_fcgi:error] [pid 1627:tid 140055163668224] [client 1.2.3.4:51614] AH01071: Got error 'PHP message: PHP Fatal error:  Uncaught PDOException: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '(?)\n          AND active = '1'' at line 4 in /var/www/example.com/index.php:65\nStack trace:\n#0 /var/www/example.com/index.php(65): PDO->prepare()\n#1 {main}\n  thrown in /var/www/example.com/index.php on line 65', referer: https://example.com/

There I have the following code:

```php
    // Check to see if the user's password is using the old md5 hashing
    $stmt = $pdo->prepare("
        SELECT id
        FROM users
        WHERE username = :new_username
          AND `password` = password(:new_password)
          AND active = '1'");
    $stmt->bindValue('new_username', $new_username, PDO::PARAM_STR);
    $stmt->bindValue('new_password', $new_password, PDO::PARAM_STR);
    $stmt->execute();
```

I have PHP v7.4.3-4ubuntu2.18 and MySQL  8.0.32-0ubuntu0.20.04.2.

**Comment by ilhanyumer** [comment]
May this is the reason: https://stackoverflow.com/a/52320680/233286 It says that the `password` function in MySQL has been deprecated.

**Comment by proactivematter** [comment]
I also can't log in on a fresh install. This issue is past a year old and it's such a shame because this looks like such a great piece of software.

**Comment by gregdotca** [comment]
If this is still an issue, I would recommend upgrading to at least v4.21.0 (or, better yet, wait until the end of the week and install the newest version, v4.22.

v4.20 included quite a few PHP, MariaDB, and MySQL compatibility updates, including some password work.
