### ISSUE TITLE
[Feature Request] Support active24.com API

### ISSUE THREAD

**Issue by butorov** [domainmod/domainmod#168]
Hello,

There is a registrar [active24](https://www.active24.com/en), actively used in particular in the Czech Republic. They have API for domain management - [Swagger UI](https://api.active24.com/).

I'm wondering if we can set up automatic domain list retrieval for this registrar (Domain Queue). If it's doable, I can draft a proposal for a pull request to merge it into the trunk.

**Comment by gregdotca** [comment]
I've moved this request over to our support portal: https://support.domainmod.org/b/90pj1r0j/domainmod-support/add-active-24-api-support

API integrations get done based on the number of users who request them, so I would recommend voting on the above ticket in order to help with visibility.
