### ISSUE TITLE
Namecheap Managers and GoDaddy Delegates?

### ISSUE THREAD

**Issue by mbressman** [domainmod/domainmod#169]
I basically just want to use DomainMOD to keep track of domains for clients so I know when they have upcoming renewals, etc. I have most of our clients using either Namecheap or GoDaddy, but the domains are in their own accounts. For Namecheap I have access to client domains via their "manager" feature, and for GoDaddy I have access via their "delegate" feature - so I can see the domains for clients for each registrar in my account. Will the GoDaddy and Namecheap API's transfer/update these domains to DomainMOD?

**Comment by gregdotca** [comment]
I'm not familiar with the exact access that's allowed with "manager" and "delegate" levels with these registrars, but if they include API access, it may be possible.
