### ISSUE TITLE
SMTP Server Settings ->SMTP Server Port (3) too short

### ISSUE THREAD

**Issue by KloonDuino** [domainmod/domainmod#17]
Hi,

Great software, thank you!

Port number for my Mailgun.com smtpserver is 4 chars long :)
And the settings in Dom only allow for three.

**Comment by chetcuti** [comment]
This was fixed and pushed out earlier today, so if you upgrade to the newest version you'll be able to enter an SMTP port up to 5 characters.

Thanks for the report!

**Comment by KloonDuino** [comment]
thank you!
