### ISSUE TITLE
Inactive Domains not displayed

### ISSUE THREAD

**Issue by floppy86** [domainmod/domainmod#173]
Hi,

I'm running "DomainMOD Version: 4.21.0 (4.21.0)" and I can't find anywhere domains that I imported with status 0

any help ?

**Comment by gregdotca** [comment]
By default, only "Live" domains are displayed. You'll need to use the Advanced Filtering on the main domain page in order to view domains that are marked as expired, sold, etc.

![domain_status](https://github.com/user-attachments/assets/c5958a2d-f853-4aeb-a8df-ebb3e3b470e6)
