### ISSUE TITLE
I'm so completely and hopelessly lost!

### ISSUE THREAD

**Issue by benwilsonnz** [domainmod/domainmod#18]
Mate I appreciate this is all second nature to you but this is seriously not cool eh. I don't understand your readme file little makes sense to me and I have something that;s not working and I don't even know where to from here?

**Comment by KloonDuino** [comment]
I think it would be better to explain your problems with the software in stead of sharing your psychological condition with the world.

**Comment by chetcuti** [comment]
Ben, what part exactly are you getting stuck on?

The installation steps in the README are pretty standard for a piece of software written to be run from a web server, so without further information regarding what's tripping you up it's fairly difficult to help troubleshoot the installation.
