### ISSUE TITLE
Ability to add SSL certificates without having to add the domain

### ISSUE THREAD

**Issue by mihail-minkov** [domainmod/domainmod#19]
In my case I have several certificates that are for clients' sites and I don't have control over their domains.

I think a good option would be to either use an inserted domain or just an identifier.

**Comment by chetcuti** [comment]
With the way the data is all linked in the backend this isn't possible, however you could create a fake/dummy domain and link the SSL certificates to it. You may also want to create a fake/dummy registrar and registrar account, that way you could have the domain fee set to 0 and it wouldn't affect your DomainMOD monetary reporting.

Something I do for clients myself is actually keep track of their domains and expiry dates, even if I don't have control of the domains, that way if I notice their domains are going to expire soon I can give them a little nudge, which is generally really appreciated.

Unfortunately though, at least in the short term, adding an SSL certificate without associating it with a domain won't be possible.
