### ISSUE TITLE
A few requests

### ISSUE THREAD

**Issue by aljawaid** [domainmod/domainmod#20]
Hello, great software.

Just tried the cron and noticed the e-mails are signed by the developer :)

Would be nice if we could:

- [ ] Have a Setting to change the DomainMOD title
- [ ] Allow the user's name to be signed in the e-mail instead of the software developer's name
- [ ] Allow the user's email to be used instead of the software developer's e-mail
- [ ] Make the text a bit more clearer/visible.  The font used doesn't seem to display clearly in FF (v51.0.1)

Your considerations would be appreciated.

**Comment by chetcuti** [comment]
I've made a note of the first 3 suggestions and I'll look into those for the future. To be honest you're the only person that's ever asked for this functionality, so it unfortunately won't be very high on the priority list.

For the 3rd suggestion, although you can't change the email address in the email itself, you **can** set the email address that's used for the FROM and REPLY-TO addresses on the email. To do so, on the main menu click Administration -> System Settings, and then set the "System Email Address".

As for the 4th suggestion, I'm not sure if I understand the problem. I've tested in FF on multiple computers and everything seems to work ok for me, even on various resolutions. I've also never had anyone else mention this before, so the issue may be with your display or resolutions settings, not the font itself.
