### ISSUE TITLE
Automatically Update whois data

### ISSUE THREAD

**Issue by jpscharf** [domainmod/domainmod#21]
How hard would it be to integrate https://jsonwhois.com to update domain expiration?

**Comment by mike503** [comment]
Or phpwhois is an option as well.

**Comment by chetcuti** [comment]
This is actually something that's planned for the future. I've already done a similar custom integration for someone using [Bulk Whois API](https://bulk-whois-api.com), though it's just to retrieve data for informational purposes, it doesn't update DomainMOD's database with expiration dates or any other important information.

One of the issues with using a 3rd party like this is that none of them cover all TLDs, so it wouldn't be a complete solution, plus if there are any problems during the connection that cause something like an expiry date to be recorded incorrectly, that could potentially cause someone to lose a domain, which is something I want to avoid at all costs. There are of course ways to validate the data before anything gets updated, but having live data updated based on another tool's information still makes me somewhat nervous.

Regarding phpWhois, this is something I've looked into as well, though it has some of the same challenges as using a 3rd party WHOIS information provider, plus the project hasn't been updated for almost 2 years, which is my main concern with it. Numerous people have asked about the future of the project and nobody seems to respond, and I'm hesitant to integrate a library into DomainMOD that may very well be abandoned.

I should note though that although 3rd party WHOIS services are planned for the future, there's a chance this functionality may not be part of the open source version of the software, but instead will be an add-on.
