### ISSUE TITLE
Add Domains To Queue button on the Domains page does not appear

### ISSUE THREAD

**Issue by tinjaw** [domainmod/domainmod#22]
I have installed domainmod ten times using Softaculous and I can never get it working. I have configured the cron job. Add Domains To Queue button on the Domains page never appears. I cannot add any domains using the APIs.

**Comment by chetcuti** [comment]
Assuming you've already added a registrar and registrar account, and have configured the registrar's API, what you've encountered is a bone-headed bug on my part. The domain queue functionality is all still there, it's just that there's no link to it anywhere, which I didn't realize until just now.

There are two ways around this issue..

1) Login to DomainMOD and then access the /queue/ directory manually by editing the URL in your web browser (so if you installed DomainMOD in http://example.com/domainmod/ you would access http://example.com/domainmod/queue/).

2) Add a single domain manually, and then the **Add Domains To Queue** button will appear on the main Domains page.

Thanks for the report! I'm not sure how long I would've gone before I noticed this.

**Comment by chetcuti** [comment]
This has now been fixed in v4.04.001, which I just released. If you don't want to deal with the manual workarounds mentioned above you can download v4.04.001 and you should be all set.
