### ISSUE TITLE
Request: Wanted domain list 

### ISSUE THREAD

**Issue by Satal** [domainmod/domainmod#23]
One thing that I would find incredibly useful for this would be the ability to list domains that I want but are currently taken. Based on this list if any of the domains get within a pre-determined number of days of expiration then I am notified.
An example of where this would be useful is where you have a domain like your name and someone else has it for you to get notified if it lapses and becomes available for you to pick up.

**Comment by lucentminds** [comment]
Something like this? I use this to monitor domains. It notifies me when any domain on my list changes in any way.
https://research.domaintools.com/monitor/domain-monitor/

**Comment by chetcuti** [comment]
It's possible that something like this may get added in the future, but it's definitely not a priority at the moment. There are quite a few other tools and services out there that already do this, and there hasn't been much interest for something like this to be added to DomainMOD, so we would rather focus on the core features for now.

In addition to the service that @lucentminds mentioned, you may also want to look into a drop catching service like http://pool.com. Pool is free to add domains, and then if it's able to successfully catch a dropped domain for you they charge you $60. If it's a domain you really want though, it's more than worth the cost.
