### ISSUE TITLE
How to get the API Credentials for a Namecheap Registrar Account

### ISSUE THREAD

**Issue by marktopper** [domainmod/domainmod#28]
Is there any guide on how to find the API Credentials for a Namecheap Registrar Account?

**Comment by dcgavril** [comment]
You have to request access to the API:

Namecheap account login > Profile > Tools > Namecheap API Access > Activate/Request  - > API access request is under review. This may take up to 2 business days. 

In fact, it could take be more than 2 days...

**Comment by marktopper** [comment]
But from Namecheap I only got a `API Key`. I cannot seem to find the `API App Name` and `API Secret` that DomainMOD requires for the Namecheap Registrar Account API Credentials.
<img width="1244" alt="screen shot 2017-06-28 at 12 08 24" src="https://user-images.githubusercontent.com/2232539/27631947-8f4c5968-5bfa-11e7-9551-9c044c747fc9.png">

**Comment by dcgavril** [comment]
The app name and secret are not for Namecheap, just add the key in the DomainMOD configuration panel. (be sure that you setup correctly the cron job so that it will fetch the data, or just start it manually).

**Comment by marktopper** [comment]
Thanks 👍
