### ISSUE TITLE
Domain list is empty

### ISSUE THREAD

**Issue by marktopper** [domainmod/domainmod#29]
I have imported my domains, but somehow the list of domains is empty, meanwhile the dashboard shows that there are 3 domains which expires in the next 60 days.

Any idea what I have done wrong?

<img width="438" alt="screen shot 2017-06-28 at 12 51 56" src="https://user-images.githubusercontent.com/2232539/27633767-dc0435cc-5c00-11e7-8897-b747b24ce824.png">
<img width="399" alt="screen shot 2017-06-28 at 12 51 48" src="https://user-images.githubusercontent.com/2232539/27633768-dc19b4ba-5c00-11e7-9b65-a6587a22ba99.png">

**Comment by jennec** [comment]
I have the same problem on a fresh installation of v4.06.01

**Comment by marktopper** [comment]
I am also using a fresh install

**Comment by jennec** [comment]
For me this also prevents me from adding any additional domains, as the links to add domains is no longer present.

**Comment by jennec** [comment]
FYI:  I added a larger number of domains by using the Domain Queue feature, and now I am able to see some, but not all, of the domains in the domains view.  Plus the buttons for adding and removing domains etc are back.  I can currently see 12 out of 46 domains.

**Comment by marktopper** [comment]
Can you see any different between the domains that you can see and the domains you cannot see?
Maybe this could help us debug this?

**Comment by jennec** [comment]
I can now see all of them.  I noticed that all the domains I could see were the ones were I had actually entered in domain fees.  After entering domains fees for all missing TLDs I could see all the domains.

**Comment by marktopper** [comment]
Thanks for sharing, managed to get it working as well by entering fees. 👍
