### ISSUE TITLE
Error during install - Unable to install

### ISSUE THREAD

**Issue by jennec** [domainmod/domainmod#30]
Hi,  

New installation on Ubuntu 17 (version abailable as of todays date).  Installed LAMP via Ubuntu setup menu.  When installing domainmod I can see the install page, fill in the email address as requested, and click on the install button only to be greeted with an HTTP 500 error.  The apache log file give me this entry:

[Wed Jun 28 10:18:34.243130 2017] [:error] [pid 2581] [client 10.201.2.5:54268] PHP Fatal error:  [ERROR]: Field 'notes' doesn't have a default value in /var/www/html/domainmod/classes/DomainMOD/Error.php on line 42, referer: http://domains.studygroup.com/domainmod/

Looking through GIT Issues and Forum entries this error suggests that MySQl is too strict.  So I added this line to /etc/mysql/my.cnf:

sql-mode="NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION"

But this has not made an difference.  I still get this error.  Are you able to advise what I might be able to do to be able to install DomainMOD?

**Comment by jennec** [comment]
Actually, ignore this.  I put the statement sql-mode="NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION" in the [mysql] setcion when it should have been in [mysqld] and sql_mode="NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION" instead.  Closing the issue.

**Comment by haynes11** [comment]
Hi,

I'm having the exact same problem and that doesn't seem to have made a difference? Is it /etc/my.cnf you edited?

**Comment by jennec** [comment]
In the file /etc/mysql/my.cnf i added sql_mode="NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION" within the section called [mysqld].

**Comment by haynes11** [comment]
Thanks! Fixed! Turns out my Cpanel/WHM had a second my.cnf file in usr/ that I had to disable for it to pick that up.
