### ISSUE TITLE
Bug: SMTP: Not sending emails

### ISSUE THREAD

**Issue by jennec** [domainmod/domainmod#31]
We have an internal SMTP relay server and allowed the IP address of the DomainMOD web server to relay through it.  Other services use this relay without any issue.
I have setup SMTP settings in DomainMOD, but when I reset an password, for example, or expect an scheduled email to arrive nothing happens.The following error text is displayed:

"Message could not be sent.  Please check your SMTP server and account information and try again."

My internal SMTP server does not require any authentication, as we specifically restrict relay access to an IP address ACL.  Could this be that the connection string in domainMOD is trying to pass no existent credentials and thus causing a failure in connection?

I checked our SMTP relays log file and found that domainmod is trying , but closing the connection before actually sending the email.  Example from the logs (I have obfuscated mail server and email addresses fro the log):

4548 01:41:08.880 Thread 4548 running on 30 Jun 2017 (using v7.3.5.7612) for new message.
4548 01:41:08.880 DOS - IP whitelisted. <DomainMOD IP> will not be evaluated.
4548 01:41:08.880 TX: <220 SMTP_RELAY_IP_ADDRESS ESMTP Service Ready>
4548 01:41:08.880 RX: <EHLO domains.studygroup.com>
4548 01:41:08.880 TX: <250-SMTP_RELAY_ADDRESS Hello DomainMOD_URL (DomainMOD_IP_ADDRESS)
250-STARTTLS
250 SIZE
>
4548 01:41:08.880 RX: <STARTTLS>
4548 01:41:08.880 TX: <220 Ready to start TLS>
4548 01:41:08.927 TLS negotiation successful.
4548 01:41:08.927 TLS version: TLSv1.2, TLS cipher: AES128-GCM-SHA256
4548 01:41:08.927 Error talking to client DomainMOD_IP_ADDRESS
Socket closed unexpectedly
4548 01:41:08.927 Thread exiting for 10.16.0.30 after 47 millisecs

**Comment by chetcuti** [comment]
> Could this be that the connection string in domainMOD is trying to pass no existent credentials and thus causing a failure in connection?

Very possible that this is the issue. To be honest I'm somewhat apprehensive about implementing the fix from pull request https://github.com/domainmod/domainmod/pull/38, it just seems like this could be opening up some potential security risks, and I'd like to investigate further before making a decision.

For now, that means you would either need a POP account that uses a username and password for authentication, or the server that hosts DomainMOD would need to have PHP's internal mail function setup and functioning properly.

I'll keep you posted.

**Comment by chetcuti** [comment]
After thinking about this further, I will not be modifying DomainMOD to allow for relay accounts. For security purposes you will either need an email account with a username and password that requires authentication, or a local working PHP mail function on the server, in order to send emails from DomainMOD.
