### ISSUE TITLE
Bug: DNS Profiles: Unable to edit view profile

### ISSUE THREAD

**Issue by jennec** [domainmod/domainmod#33]
After adding a DNS profile I cannot view/edit it.  I can see it in the DNS Profile list, but cannot do anything with it.
I have 50 or so DNS profiles created after using Domain Queue processing. A lot of them are duplicates, but I cannot tidy them up.  

The error in Apache log is:
[Mon Jul 03 06:35:31.650493 2017] [:error] [pid 18395] [client 10.0.154.116:51342] PHP Fatal error:  Uncaught PDOException: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'domainmod.dw_accounts' doesn't exist in /var/www/domainmod/classes/DomainMOD/DwAccounts.php:182\nStack trace:\n#0 /var/www/domainmod/classes/DomainMOD/DwAccounts.php(182): PDO->prepare('\\n            SE...')\n#1 /var/www/domainmod/domains/edit.php(590): DomainMOD\\DwAccounts->checkForAccounts('internationalst...')\n#2 {main}\n  thrown in /var/www/domainmod/classes/DomainMOD/DwAccounts.php on line 182, referer: http://domains.studygroup.com/domains/

followed by:

[Mon Jul 03 07:05:55.736701 2017] [:error] [pid 18351] [client 10.0.154.116:56447] PHP Fatal error:  Uncaught Error: Call to a member function prepare() on null in /var/www/domainmod/assets/edit/dns.php:162\nStack trace:\n#0 {main}\n  thrown in /var/www/domainmod/assets/edit/dns.php on line 162, referer: http://domains.studygroup.com/assets/dns.php

**Comment by chetcuti** [comment]
This was indeed a bug. There was a required line of code that was accidentally omitted during a system-wide update, but it was added in the most recent release ([v4.07.00](https://github.com/domainmod/domainmod/releases/tag/v4.07.00)). If you [upgrade](https://domainmod.org/upgrade/) everything should work.
