### ISSUE TITLE
Feature Request: Update existing domains status via API

### ISSUE THREAD

**Issue by jennec** [domainmod/domainmod#35]
Would it be possible to have a scheduled task that would update domains obtained via the registrars API when they renew, expire, transfer etc.  

A scheduled task once a day would be perfect.

**Comment by marktopper** [comment]
This would indeed be a good idea since we already have the API.

**Comment by chetcuti** [comment]
This is absolutely planned for the future! Unfortunately I don't yet have an ETA on when it will be implemented, but it's something that I know a lot of people would benefit from and it's already on the todo list.
