### ISSUE TITLE
Wrong Link when alert to display says "If you've already updated all new TLDs, you should update the domain fees system-wide (this may take some time). "

### ISSUE THREAD

**Issue by fingersonfire** [domainmod/domainmod#4]
I got the alert to add missing fees after adding. I've done so. 
However the message does not disappear. So there is link below to upgrade system-wide.

The link to update system wide is pointing to 
http://domainmod.instance.com/settings/maintenance/update-domain-fees.php

instead of
http://domainmod.instance.com/maintenance/update-domain-fees.php

**Comment by chetcuti** [comment]
Unfortunately a couple URLs were pointed at their old locations, but this has now been fixed as of v4.01.003 (716381becbe4a349e030ab9eb520f4113511b162).

Thanks for the report!
