### ISSUE TITLE
Godaddy API domain list limit

### ISSUE THREAD

**Issue by japettyjohn** [domainmod/domainmod#46]
When trying to import domains in to the domainqueue using the GoDaddy API I found the result from godaddy was an error that the limit had to be no more than 1000, but it's [hardcoded to 10,000](https://github.com/domainmod/domainmod/blob/master/classes/DomainMOD/GoDaddy.php#L39) in the app.

Something I can change on the account or should I do a PR?

**Comment by chetcuti** [comment]
Sorry about that japettyjohn, I didn't notice that GoDaddy's limit was 1,000, so yes, the hard-coded limit of 10,000 is invalid. I've updated this to 1,000 and it will be fixed in the next release, which shouldn't be happening fairly soon.

**Comment by chetcuti** [comment]
Reopening this issue so that I remember to comment and update the thread when the newest version gets released.

**Comment by chetcuti** [comment]
This was fixed in v4.08.00, which was released today.

**Comment by junitseo** [comment]
How can I get the total number of my domains?
