### ISSUE TITLE
Bug: Can't Install. Install Page giving 500 error after typing in e-mail Install log says...

### ISSUE THREAD

**Issue by haynes11** [domainmod/domainmod#47]
[07-Sep-2017 12:37:56 UTC] PHP Fatal error:  [ERROR]: Field 'notes' doesn't have a default value in /home/techsu/public_html/domaintracker/domainmod/classes/DomainMOD/Error.php on line 42

**Comment by Sugiyu** [comment]
Same here.
I think categories table has "NOT NULL" restriction on notes field, but next sentence try to insert a record with "NULL".
Line 181
  `notes` LONGTEXT CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL,

Line 190
    $sql = "INSERT INTO `categories`
            (`name`, `stakeholder`, `creation_type_id`, `insert_time`)
            VALUES
            ('[no category]', '[no stakeholder]', '" . $creation_type_id_installation . "', '" . $timestamp . "');";
    $result = mysqli_query($dbcon, $sql) or $error->outputSqlError($dbcon, '1', 'ERROR');

**Comment by haynes11** [comment]
I have exactly what you have in my install/index.php as above. So how do we fix this?

**Comment by Sugiyu** [comment]
I'm not sure whether this is right way, but it worked when I removed "NOT NULL" restriction.

**Comment by haynes11** [comment]
I think I'm still getting an error. Can you give me your copy?

**Comment by Sugiyu** [comment]
Did you drop Database?
Create database might be succeeded partially and it might still have NOT NULL restriction on that table.
I will send my file to you later.

**Comment by Sugiyu** [comment]
See the attached file.

2017-09-13 12:11 GMT-07:00 haynes11 <notifications@github.com>:

**Comment by haynes11** [comment]
Hi,

There's nothing attached for me?

I tried dropping everything in the database and deleting anything with "NOT NULL" with no luck. How odd!

**Comment by Sugiyu** [comment]
[index_php.txt](https://github.com/domainmod/domainmod/files/1301579/index_php.txt)
Please update file name and put it on /domainmod/install/ directly, then drop database and create it again.

Hope this can solve the issue. Once again, I'm not sure whether this is right way...

**Comment by haynes11** [comment]
Actually it turns out the entire fix to this is to turn off sql strict mode. Look here for the fix #30 

On a WHM/Cpanel server there is the usual /etc/my,cnf but also cpanel/WHM also has /usr/my.cnf or something along those lines that you have to disable or it won't pick up the changes you made in /etc/my.cnf

**Comment by chetcuti** [comment]
As mentioned by @haynes11, this can be fixed by disabling MySQL strict mode. Please see the [Troubleshooting Guide](https://domainmod.org/docs/userguide/troubleshooting/) on how to do this.
