### ISSUE TITLE
Namecheap won't import via API

### ISSUE THREAD

**Issue by haynes11** [domainmod/domainmod#49]
I can't pull data through from namecheap I just get "

error | Unable to get domain list
-- | --

"

as the error in debug log. API key is correct. Unknown what to put in API secret (Tried the API key in both and still didn't work) Is this a broken feature?

Best,
J

**Comment by lucentminds** [comment]
Looks like you can leave __secret__ blank or put anything in there. Domainmod doesn't use it with the namecheap api. All it needs is the __registrar username__ and the __api key__.

Note: When adding or editing the api credentials, make sure you select an ip from the __API IP Address__ drop down.


```text
# Initial url

https://api.namecheap.com/xml.response?
   &ApiUser=registrar_username
   &ApiKey=api_key
   &UserName=registrar_username
   &Command=namecheap.domains.getList
   &ClientIp=-
   &PageSize=100
```

**Comment by haynes11** [comment]
Hi,

All those details are filed in correctly. 

See attached. Any advice?
![namecheapapi2](https://user-images.githubusercontent.com/19718532/31311909-51b3c22c-abae-11e7-9693-da0d8b6008da.png)
![namecheapapi1](https://user-images.githubusercontent.com/19718532/31311910-51c878de-abae-11e7-83ce-956aa80655a5.png)

**Comment by lucentminds** [comment]
Looks good. Now move up the page to where it says __Username (100)__. Make sure this is the same as the api username.

**Comment by haynes11** [comment]
Hi yeah that username in there is correct. What's odd is that if I run the api call manually in my browser - ( white listed my PC IP) https://api.namecheap.com/xml.response?ApiUser=&ApiKey=&UserName=&Command=namecheap.domains.getList&ClientIp=7&PageSize=100

Then it runs fine...

I'm also not sure that my crons are not running randomly again as debug log never show any updates unless I run things via the task scheduler - which the last run time never updates unless I manually run it. The cron job is 100 % running as I get the e-mail notification to tell me it's run every 10 minutes.

Best,
J

**Comment by haynes11** [comment]
Hi,

I own this whole web server and all IP addresses fyi.

I've managed to get this working. Rather than hand out real ip's I'm going to use some sample ones.

Let's say my WHM/Cpanel servers host ip is: 1.2.3.4

techsu.net sits on a dedicated ip address let's say that is 1.2.3.5

domaintracker.techsu.net is a subdomain of techsu.net so naturally sits on the same ip address of 1.2.3.5 right?

Here's what I'm confused by. As a shot in the dark, I decided to try to whitelist on the NAMECHEAP API end 1.2.3.4 (The WHM/Cpanel servers host IP)

The settings in domain mod still reside to techsu.net main IP of 1.2.3.5 so no change there.

Tried running the import...and it worked.

The Cpanel/WHM server has CSF firewall installed but I don't see that making a difference. I'm very confused by this because Namecheap's API is referring to the dedicated IP address of that domain which theoretically should be all you need. So as for why adding the Cpanel/WHM servers host IP to the namecheap API whitelist suddenly makes it worked I'm a little baffled...

Do you have any ideas why that works?

Best,
J

**Comment by haynes11** [comment]
I don't think there's any funky networking going on it's fairly standard. So still confused why this works with the WHM/Cpanel hostname master ip and not specifically with the dedicated IP address that domain has. This isn't meant to work that way is it?

**Comment by lucentminds** [comment]
I can't think of anything.

**Comment by chetcuti** [comment]
@haynes11 that _is_ rather odd, as in your example Namecheap should be getting contacted by 1.2.3.5 and not 1.2.3.4. Is it possible that your web server is configured so that cron jobs all run from your server's primary IP instead of here the cron files are located?

**Comment by haynes11** [comment]
@chetcuti It's a cpanel/WHM server that I manage. To be honest I've never thought about what cron jobs run as. I assumed as they run under whatever cpanel user account that they would run under the dedicated IP attached to xyz account also. Think I'll investigate on my side as it would be interesting/useful to know! :) Thanks for the idea!
