### ISSUE TITLE
Can't Install - how to debug?

### ISSUE THREAD

**Issue by aphilsmith** [domainmod/domainmod#50]
My install page is blank.  Besides creating a database and setting values in config.inc.php, the documentation should describe full setup details and how to enable debug logs.

**Comment by januridp** [comment]
same with me. http://localhost/domainmod got blank also for http://localhost/domainmod/install folder.

**Comment by januridp** [comment]
update:
i did success installation.

try to download .zip from https://domainmod.org/download/

**Comment by aphilsmith** [comment]
I use  git to try version 4.07.00 . Still no luck. The install URL is blank. There should be more details about 1) how to initialize the database, 2) how to modify config.inc.php and 3) how to enable debug logs to see what went wrong, and 4) detail the sysadmin email address (what if your system doesn't have sendmail?). If there are any other configuration changes need, please document.

**Comment by chetcuti** [comment]
I'd suggest trying the first item in the troubleshooting guide (disabling MySQL strict mode), which I think may be the issue here.

https://domainmod.org/docs/userguide/troubleshooting/

If that doesn't work check the PHP error logs and post any errors you're getting, which will help with troubleshooting the issue.

**Comment by aphilsmith** [comment]
That worked! Thanks.

**Comment by aphilsmith** [comment]
It looks OK. However, I want to manage my intranet and it seems to expect a
registrar. What can I use?

**Comment by chetcuti** [comment]
Sorry @aphilsmith, I'm not sure what you mean (re: intranet vs. registrar). If you can include some more information regarding what exactly it is you're trying to do I'll see if I can help.

**Comment by aphilsmith** [comment]
I want to manage domains in my private network (intranet). I shouldn't need a registrar for this. I have my own DNS server. Is there a way I can be my own registrar?

**Comment by aphilsmith** [comment]
I want to manage domains in my private network (intranet). I shouldn't need a registrar for this. I have my own DNS server. Is there a way I can be my own registrar?

**Comment by chetcuti** [comment]
Oh, so you're trying to manage an internal network domain(s)? (ie. "_On a local area network (LAN), a domain is a subnetwork made up of a group of clients and servers under the control of one central security database._")

If so, unfortunately that's not what DomainMOD is designed for. It's designed to manage a large portfolio of domain names (github.com, domainmod.org, etc.) and other internet assets such as SSL certificates, web hosting accounts, and so on. If you're trying to use it to manage a LAN domain or multiple LAN domains I'm not sure if it's going to work for you.

**Comment by aphilsmith** [comment]
We have an Intranet that spans 3 continents and will have thousands of
nodes. We have a unique public-private architecture and will be doing
domain sales and auctions for namespace on our network. Basically, we will
be operating as an ISP. So, we need to have the ability to handle billing,
accounting and provisioning of those domains, which could be *anything *(even
dotcom names that mirror ones on the public Internet). DomainMod seem s to
suite our purposes exactly. We need to work around the registrar
requirement, or find Open Source software that would allow us to be our own
registrar.

**Comment by chetcuti** [comment]
In order to get around the registrar requirement all you need to do is create a sample/test registrar, then do the same for a registrar account, and then you can begin to add domains and their fees (which can be set to $0). I would recommend adding a few sample domains and then playing around with the software a bit to see if it would suit your needs. I still have a feeling that it might not be quite what you're looking for.
