### ISSUE TITLE
Supported Authentication Methods (e.g. LDAP, Active Directory)?

### ISSUE THREAD

**Issue by broberts-mrmc** [domainmod/domainmod#53]
I've looked through and searched the documentation, but didn't find that it was mentioned. Does DomainMOD support external authentication methods such as LDAP, including Active Directory, etc?

If not, has it ever been requested? And, if not, would you entertain a pull request to add it?

Of course, my recommendation would be that it be something that's configurable in the application to the point that those who wish to use DomainMOD's default, internal authentication method would be able to do so without any extra/special configuration or steps.

**Comment by chetcuti** [comment]
DomainMOD currently doesn't support LDAP/Active Directory/etc. for authentication, and to be honest it may never. The target market for DomainMOD generally won't be using an external authentication method, so it's not currently very high on the priority list, and adding it will add quite a bit of overheard to the application as a whole.

I'm keeping this on the todo list so that I keep it in mind for the future, but I regret to say that it probably won't be happening anytime soon.

**Comment by broberts-mrmc** [comment]
Thanks for the quick reply. Should I interpret it as saying you probably won't contribute LDAP or external authentication support anytime soon **AND** you would not consider merging a pull request if I contributed LDAP or external authentication support to the project?

For what it's worth, in other projects, I've implemented LDAP/external authentication methods concurrent with internal authentication.  The overhead is minimal and typically requires only a few classes, minimal implementation code and a server with the LDAP extension for PHP enabled (http://php.net/manual/en/book.ldap.php).

These past implementations I've always favored a default configuration with internal authentication "out-of-the box" so the code just works without additional configuration steps.  Of course, those who wish to use LDAP/external authentication must configure appropriately, usually by specifying a few details about the authentication service or API such as, for example, host name(s), domain qualifier, credentials or API key.

**Comment by broberts-mrmc** [comment]
I don't intend this as confrontational by any means. I'm left to assume that the lack of response to my last comment, at least to this point, should be taken as an implicit: *"No, I would not consider a pull request implementing LDAP or external authentication support"*.

It seems maybe a fork compatible with Gnu GPL v3 is a better way to go? In any case, thanks for your time. Good luck with your project!
