### ISSUE TITLE
Installation failure

### ISSUE THREAD

**Issue by Splix76** [domainmod/domainmod#56]
Get first page where I am prompted for admin password, upon entering the password I get the following error. I have confirmed that php-pdo is installed. 

> PHP Fatal error: Uncaught PDOException: SQLSTATE[HY000]: General error: 1364 Field 'notes' doesn't have a default value in /var/www/domainmod/install/index.php:189\nStack trace:\n#0 /var/www/domainmod/install/index.php(189): PDO->query('\\n            IN...')\n#1 {main}\n  thrown in /var/www/domainmod/install/index.php on line 189

**Comment by Splix76** [comment]
Based on this forum post: https://groups.google.com/forum/#!searchin/domainmod/install%7Csort:date/domainmod/p5MPYpafrmk/NvaaOD9gBwAJ

I dove into and checked out the database. I do get the following tables created.
+----------------+
| Tables_in_dmod |
+----------------+
| categories     |
| creation_types |
| user_settings  |
| users          |
+----------------+

There are a high number of duplicate entries due to the number of times I attempted to install. I am going to drop all tables and re-try.

**Comment by Splix76** [comment]
Clearing the database out did not resolve the error. The error message is the same, there appears to be an issue with the 'notes' field not having a default value.

**Comment by Splix76** [comment]
Working with a good friend I found that the issue is the code tries to set a default value for a 'longtext' type of column. Changing 'notes' to varchar fixed this, however it errors on every longtext column out there of which I am at more than 6 errors in the setup now.

**Comment by Splix76** [comment]
Below are all the longtext coluomns that I am having issues with, it maybe a php conf issue causing this.

>                 `notes` LONGTEXT CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL,
>                 `notes` LONGTEXT CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL,
>                 `notes` LONGTEXT CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL,
>                 `notes` LONGTEXT CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL,
>                 `notes` LONGTEXT CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL,
>                 `notes` LONGTEXT CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL,
>                 `notes` LONGTEXT CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL,
>                 `notes` LONGTEXT CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL,
>                 `notes` LONGTEXT CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL,
>                 `notes` LONGTEXT CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL,
>                 `notes` LONGTEXT CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL,
>                 `notes` LONGTEXT CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL,
>                 `notes` LONGTEXT CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL,
>                 `notes` LONGTEXT CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL,
>                 `description` LONGTEXT CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL,
>                 `segment` LONGTEXT CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL,
>                 `notes` LONGTEXT CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL,
>                 `notes` LONGTEXT CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL,
>                 `hash` LONGTEXT CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL,
>                 `notes` LONGTEXT CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL,
>                 `description` LONGTEXT CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL,
>                 `notes` LONGTEXT CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL,
>                 `agent` LONGTEXT COLLATE utf8_unicode_ci NOT NULL,
>                 `message` LONGTEXT CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL,
>                 `extra` LONGTEXT CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL,
>                 `url` LONGTEXT CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL,

**Comment by Splix76** [comment]
This was in Amazon Linux (which I dislike but am forced to use.) Fix for this was to remove strict from sql_mode.

`SET GLOBAL sql_mode = 'ONLY_FULL_GROUP_BY,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION'`

**Comment by Splix76** [comment]
Setting this via SQL CLI did not hold settings through a mysqld restart.

Adding the below to the /etc/my.cnf got them to be persistent.

`sql-mode='ONLY_FULL_GROUP_BY,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION'`

**Comment by Splix76** [comment]
Do yourself a favor and just set the line to this to avoid issues with the app.

`sql-mode='NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION'`

**Comment by chetcuti** [comment]
Yeah, unfortunately having strict mode enabled in MySQL will cause some issues, and disabling strict mode is what we recommend as well.

https://domainmod.org/docs/userguide/troubleshooting/#strictmode
