### ISSUE TITLE
Import csv or excel files for quick import of domain lists

### ISSUE THREAD

**Issue by Aeval** [domainmod/domainmod#68]
Hey,

I was thinking an uploader for domain lists from registrars without an API or with an unsupported API. I'm currently trying to import a large list of domains from BulkRegistery and they don't have an API DomainMOD supports. The ability to quick upload a list would be great!

Thank you!

**Comment by chetcuti** [comment]
This feature is actually very close to the top of the list of things to be implemented now! If you'd like to be notified when CSV importing is added I would recommend subscribing via one of the methods on [this page](https://domainmod.org/subscribe/).

**Comment by jjtroberts** [comment]
Was this feature ever implemented? We have a lot of domains at Network Solutions we'd like to import.

**Comment by chetcuti** [comment]
This is on the roadmap and is very close to happening, at least a basic version to start (ie. people will probably need to load their domain data into a CSV template). Head on over to our support portal and vote for if you'd like to help the feature get implemented sooner!

https://support.domainmod.org/roadmap/domain-csv-import
