### ISSUE TITLE
Column order

### ISSUE THREAD

**Issue by Qrzysio** [domainmod/domainmod#69]
In `Settings -> Display settings -> Columns to display` we may add/remove columns displayed on the domain/SSL list. Unfortunately, there is no way to arrange them the way we really want. 

Even removing all the columns and adding them again in a new order the script puts the columns always in the same order:  `Expiry date, Fee, TLD, Account, DNS, Category`.
So we cannot, for example, put `Category` column at the beginning. It is always at the very end.

**Comment by chetcuti** [comment]
Unfortunately you are correct, there's currently no way to change the order of the displayed columns. I do plan to figure out a way to do this eventually, but unfortunately I'm not sure how long it's going to be until that happens.
