### ISSUE TITLE
Fees rounding strange behavior

### ISSUE THREAD

**Issue by maupet** [domainmod/domainmod#7]
There is a strange rounding issue with fees, that is only visible in:  Assets / Registrars/  Fees / Edit

Some examples:
9.60 becomes 9.60000038147
8.10 becomes 8.10000038147
5.20 becomes 5.19999980927
5.35 becomes 5.34999990463

System information:
Operating System: Linux vm0740.cs09.seeweb.it 3.2.0-4-amd64 #1 SMP Debian 3.2.54-2 x86_64
Web Server: Apache
PHP: 5.4.4-14+deb7u8
MySQL: 5.5.35-0+wheezy1
DomainMOD: 4.01.003 (4.01.003)

**Comment by chetcuti** [comment]
That's very strange indeed, I've never seen that happen before.

To clarify, when you enter a fee for a domain at say, 9.60, and then you go back and edit the fee it's then displaying 9.60000038147 instead of 9.60? Is this happening with every fee you enter or just certain amounts?

**Comment by maupet** [comment]
Yes, that is exactly what is happening.

It seem to affect any rounded amount, but not integer amounts.


Il 02/09/2016 05:55, Greg Chetcuti ha scritto:

**Comment by fhadlich** [comment]
I can verify this issue, and suggest changing the datatype for the cost-specific columns in "fees" table from float to decimal(8,2)

For a good explanation on the how/why, please refer to http://stackoverflow.com/a/5150345

**Comment by chetcuti** [comment]
I've updated the field types in the database to decimal for all fees as well as the currency conversion rates. This new version will be released in the next couple days.

Thanks a lot for your help!
