### ISSUE TITLE
some errors in go.php in install process

### ISSUE THREAD

**Issue by gportail** [domainmod/domainmod#71]
Errors in go.php :

- categories.notes is 'NOT NULL' and without default values but the "insert" order after "create table" order doesn't set values for "notes".
- hosting.url is 'NOT NULL' and without default values but the "insert" order after "create table" order doesn't set values for "url".
- hosting.notes is 'NOT NULL' and without default values but the "insert" order after "create table" order doesn't set values for "notes".
- owners.notes is 'NOT NULL' and without default values but the "insert" order after "create table" order doesn't set values for "notes".
- currencies.notes is 'NOT NULL' and without default values but the "insert" order after "create table" order doesn't set values for "notes".
- ssl_cert_types.notes is 'NOT NULL' and without default values but the "insert" order after "create table" order doesn't set values for "notes".
- table 'dns' has lot of 'NOT NULL' field without default values then the "insert" order after "create table" order fail.
- ip_addresses.notes is 'NOT NULL' and without default values but the "insert" order after "create table" order doesn't set values for "notes".
- scheduler.last_duration is 'NOT NULL' and without default values but the "insert" order after "create table" order doesn't set values for "last_duration".
- table 'settings' has lot of 'NOT NULL' field without default values then the "insert" order after "create table" order fail.

Maybe you should consider to set "notes" nullable ?

**Comment by gportail** [comment]
I see issue 62.

But how to do if I can't change sql-mode ?

**Comment by chetcuti** [comment]
Thanks to the patch that @quantum5 submitted, strict mode should now get disabled automatically when DomainMOD connects to the database, so the user should rarely, if ever, have to update their MySQL config file.
