### ISSUE TITLE
install

### ISSUE THREAD

**Issue by snelweg** [domainmod/domainmod#72]
Well, that did not go well.
The upgrade failed missarably. So I did a new install, git cloned a new version, a new database and now I am stuck again.

`
==> /home/dom/logs/access_log <==
me - - [09/Aug/2018:19:56:29 +0200] "GET /install/go.php HTTP/1.1" 500 295 "-" "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36"
me - - [09/Aug/2018:19:56:29 +0200] "GET /install/go.php HTTP/1.1" 500 295 "-" "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36"
me - - [09/Aug/2018:19:56:29 +0200] "GET /install/go.php HTTP/1.1" 500 295 "-" "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36"

==> /home/dom/logs/error_log <==
[Thu Aug 09 19:56:29.319929 2018] [fcgid:warn] [pid 17749] [client me:60903] mod_fcgid: stderr: PHP Fatal error:  Uncaught PDOException: SQLSTATE[HY000]: General error: 1364 Field 'notes' doesn't have a default value in /home/dom/public_html/install/go.php:180
[Thu Aug 09 19:56:29.319976 2018] [fcgid:warn] [pid 17749] [client me:60903] mod_fcgid: stderr: Stack trace:
[Thu Aug 09 19:56:29.319983 2018] [fcgid:warn] [pid 17749] [client me:60903] mod_fcgid: stderr: #0 /home/dom/public_html/install/go.php(180): PDO->query('\\n        INSERT...')
[Thu Aug 09 19:56:29.319989 2018] [fcgid:warn] [pid 17749] [client me:60903] mod_fcgid: stderr: #1 {main}
[Thu Aug 09 19:56:29.319995 2018] [fcgid:warn] [pid 17749] [client me:60903] mod_fcgid: stderr:   thrown in /home/dom/public_html/install/go.php on line 180
[Thu Aug 09 19:56:29.532780 2018] [fcgid:warn] [pid 17891] [client me:60904] mod_fcgid: stderr: PHP Fatal error:  Uncaught PDOException: SQLSTATE[HY000]: General error: 1364 Field 'notes' doesn't have a default value in /home/dom/public_html/install/go.php:180
[Thu Aug 09 19:56:29.532890 2018] [fcgid:warn] [pid 17891] [client me:60904] mod_fcgid: stderr: Stack trace:
[Thu Aug 09 19:56:29.532900 2018] [fcgid:warn] [pid 17891] [client me:60904] mod_fcgid: stderr: #0 /home/dom/public_html/install/go.php(180): PDO->query('\\n        INSERT...')
[Thu Aug 09 19:56:29.532909 2018] [fcgid:warn] [pid 17891] [client me:60904] mod_fcgid: stderr: #1 {main}
[Thu Aug 09 19:56:29.532917 2018] [fcgid:warn] [pid 17891] [client me:60904] mod_fcgid: stderr:   thrown in /home/dom/public_html/install/go.php on line 180
[Thu Aug 09 19:56:29.725539 2018] [fcgid:warn] [pid 17716] [client me:60905] mod_fcgid: stderr: PHP Fatal error:  Uncaught PDOException: SQLSTATE[HY000]: General error: 1364 Field 'notes' doesn't have a default value in /home/dom/public_html/install/go.php:180
[Thu Aug 09 19:56:29.725614 2018] [fcgid:warn] [pid 17716] [client me:60905] mod_fcgid: stderr: Stack trace:
[Thu Aug 09 19:56:29.725624 2018] [fcgid:warn] [pid 17716] [client me:60905] mod_fcgid: stderr: #0 /home/dom/public_html/install/go.php(180): PDO->query('\\n        INSERT...')
[Thu Aug 09 19:56:29.725645 2018] [fcgid:warn] [pid 17716] [client me:60905] mod_fcgid: stderr: #1 {main}
[Thu Aug 09 19:56:29.725654 2018] [fcgid:warn] [pid 17716] [client me:60905] mod_fcgid: stderr:   thrown in /home/dom/public_html/install/go.php on line 180
`

**Comment by chetcuti** [comment]
This generally happens when MySQL strict mode is enabled on the server. As of [v4.11](https://github.com/domainmod/domainmod/releases/tag/v4.11.0), which was released last night, this should no longer be an issue. The software should now automatically disable strict mode when connecting to the database. If for some reason it's not working though, strict mode can still be disabled manually in the MySQL config file ([more info](https://domainmod.org/docs/userguide/troubleshooting/#strictmode)).
