### ISSUE TITLE
Domainmod Multilangage

### ISSUE THREAD

**Issue by AZWhosting** [domainmod/domainmod#75]
Hi, I implemented Gettext on Domainmod.

I started the translation, added a language selector ...
Would you accept my branch Dev Translation?
https://github.com/AZWhosting/domainmod/tree/Dev_Translation

If the project interests you, then I will finish the implementation of the translation on the whole site

It would be a pleasure to work together to integrate it into future versions

Cordially
![domainmod](https://user-images.githubusercontent.com/2768137/45576761-d261a100-b878-11e8-9010-aae56b12ef9d.png)

**Comment by yvangodard** [comment]
:+1:

**Comment by yvangodard** [comment]
+1 
If you search someone to translate in french, it's OK for me!
And the multilingual feature would be very nice!

**Comment by chetcuti** [comment]
I'm happy to announce that as of v4.16.0, DomainMOD now has multilingual support!
