### ISSUE TITLE
Install fails due to strict mode on MySQL 5.7

### ISSUE THREAD

**Issue by awendland** [domainmod/domainmod#9]
I spent some time debugging this error and thought I'd report it here because it wasn't initially obvious to me. The install script sets a lot of datetime columns with the default value of `0000-00-00 00:00:00` which is invalid in the latest versions of MySQL because of the [strict mode changes in 5.7](http://dev.mysql.com/doc/refman/5.7/en/sql-mode.html#sql-mode-changes). I turned off STRICT_TRANS_TABLES in the MySQL config to fix the issue. It would be nice if this potential error was mentioned in the documentation now that MySQL 5.7 is the current version.

Thanks for making this great piece of software!

**Comment by MicroKloon** [comment]
same here

**Comment by chetcuti** [comment]
Thanks a lot for troubleshooting this issue @awendland! I've updated the installation and update processes to use valid default datetime stamps, and this new version will be getting released in the next couple days.
