### ISSUE TITLE
Undefined variable: _SESSION

### ISSUE THREAD

**Issue by Qrzysio** [domainmod/domainmod#95]
A tiny fix needed. `cron.php` generates the following notice:
` Notice: Undefined variable: _SESSION in (...)/classes/DomainMOD/Log.php on line 37`

**Comment by chetcuti** [comment]
Although this notice shouldn't really cause any issues, I've implemented a fix in the development branch, and the change will be getting pushed out in a new official release in the next couple weeks.

Thanks for the report!
