### ISSUE TITLE
Uncaught Error: Call to a member function getRangeString()

### ISSUE THREAD

**Issue by alexkuc** [domainmod/domainmod#96]
I have just installed fresh version of `4.13` on my local Mac. When trying to run `Cost by Registrar`, I get the following error:

    [28-Feb-2019 01:08:39 UTC] PHP Fatal error:  Uncaught Error: Call to a member function                     getRangeString() on null in /Applications/MAMP/htdocs/domainmod/reporting/domains/cost-by-registrar.php:62
    Stack trace:
    #0 {main}
      thrown in /Applications/MAMP/htdocs/domainmod/reporting/domains/cost-by-registrar.php on line 62

System Information:

    DomainMOD Version: 4.13.0 (4.13.0)
    Local IP Address: ::1
    Remote IP Address: 139.153.121.114
    Web Server OS: Darwin d121114.stir.ac.uk 17.7.0 Darwin Kernel Version 17.7.0: Thu Dec 20 21:47:19     PST 2018; root:xnu-4570.71.22~1/RELEASE_X86_64 x86_64
    Web Server Software: Apache
    PHP Version: 7.0.8
    PHP Error Log Location: /Applications/MAMP/logs/php_error.log
    MySQL Version: 5.5.42
    MySQL Mode: NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION
    
    Server Software: PHP v5.3.2+: Pass, MySQL: Pass
    PHP Extensions: PDO (MySQL): Enabled, cURL: Enabled, OpenSSL: Enabled
    PHP Settings: allow_url_fopen: Enabled

Found the culprit:

File [cost-by-registrar.php](https://github.com/domainmod/domainmod/blob/master/reporting/domains/cost-by-registrar.php) is missing variable `$reporting`.

Here's what it looks like before my fix:

https://github.com/domainmod/domainmod/blob/c2902928f5f408ec833012a01124658f49fe9ca2/reporting/domains/cost-by-registrar.php#L29-L35

Here's how I fixed it:
```php
$deeb = DomainMOD\Database::getInstance();
$system = new DomainMOD\System();
$layout = new DomainMOD\Layout;
$date = new DomainMOD\Date();
$time = new DomainMOD\Time();
$form = new DomainMOD\Form();
$reporting = new DomainMOD\Reporting();
$currency = new DomainMOD\Currency();
```

**Comment by alexkuc** [comment]
System Information
    DomainMOD Version: 4.13.0 (4.13.0)
    Local IP Address: ::1
    Remote IP Address: 139.153.121.114
    Web Server OS: Darwin d121114.stir.ac.uk 17.7.0 Darwin Kernel Version 17.7.0: Thu Dec 20 21:47:19     PST 2018; root:xnu-4570.71.22~1/RELEASE_X86_64 x86_64
    Web Server Software: Apache
    PHP Version: 7.0.8
    PHP Error Log Location: /Applications/MAMP/logs/php_error.log
    MySQL Version: 5.5.42
    MySQL Mode: NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION
    
    Server Software: PHP v5.3.2+: Pass, MySQL: Pass
    PHP Extensions: PDO (MySQL): Enabled, cURL: Enabled, OpenSSL: Enabled
    PHP Settings: allow_url_fopen: Enabled

**Comment by alexkuc** [comment]
Found the culprit:

File `cost-by-registrar.php` is missing variable `$reporting = new DomainMOD\Reporting();`

Here's what lines 29 to 35 look like before my fix:

    $deeb = DomainMOD\Database::getInstance();
    $system = new DomainMOD\System();
    $layout = new DomainMOD\Layout;
    $date = new DomainMOD\Date();
    $time = new DomainMOD\Time();
    $form = new DomainMOD\Form();
    $currency = new DomainMOD\Currency();

Here's how I fixed it:

    $deeb = DomainMOD\Database::getInstance();
    $system = new DomainMOD\System();
    $layout = new DomainMOD\Layout;
    $date = new DomainMOD\Date();
    $time = new DomainMOD\Time();
    $form = new DomainMOD\Form();
    $reporting = new DomainMOD\Reporting();
    $currency = new DomainMOD\Currency();

**Comment by chetcuti** [comment]
Thanks for the report @alexkuc! This change is already in our development branch and will be getting pushed out in a new release in the next couple weeks.
