### ISSUE TITLE
Feature request: pananames.com api

### ISSUE THREAD

**Issue by hellmany** [domainmod/domainmod#98]
Hello, do you plan to add PanaNames.com API support ?
Here is a full documentation https://docs.pananames.com/

**Comment by chetcuti** [comment]
We don't currently have any plans to add the Pananames API, however I've now added it to the list of potential APIs to be implemented in the future, so it may happen at some point down the road! I have to admit though that there are quite a few features (including other API integrations) that are ahead of it, so it may be a while.
